/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f746xx.h"

void Usart1Config(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;//enable usart1 clock
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; //enable gpioA clock
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;//enable gpioB clock

	GPIOA->MODER |= (0b10 << 9*2); // PA9
	GPIOB->MODER |= (0b10 << 7*2); // PB7
	GPIOA->AFR[1] |= (0b111 << (4 * (9-8)));
	GPIOB->AFR[0] |= (0b111 << (4 * (7-0)));

	USART1->BRR = 1667;
	USART1->CR1 |= USART_CR1_TE;
	USART1->CR1 |= USART_CR1_RE;
	USART1->CR1 |= USART_CR1_UE;
	USART1->CR1 |= (0b00 << 28);
	while (1) {
	USART1->TDR = 11111111;

	while (!(USART1->ISR & USART_ISR_TXE));
	}

	RCC->CR |= RCC_CR_HSEON;
	while ((RCC->CR & RCC_CR_HSERDY) != RCC_CR_HSERDY);
	RCC->CFGR |= RCC_CFGR_SW_HSE;
	while ((RCC->CFGR & RCC_CFGR_SWS_HSE) == 0);
	uint32_t sws = 0, hpre = 0, ppre2 = 0, ppre1 = 0;
	sws = (RCC->CFGR & RCC_CFGR_SWS) >>
	 RCC_CFGR_SWS_Pos;
	hpre = (RCC->CFGR & RCC_CFGR_HPRE) >>
	 RCC_CFGR_HPRE_Pos;
	ppre2 = (RCC->CFGR & RCC_CFGR_PPRE2) >>
	 RCC_CFGR_PPRE2_Pos;
	ppre1 = (RCC->CFGR & RCC_CFGR_PPRE1) >>
	 RCC_CFGR_PPRE1_Pos;
}

void Usart6Config(void)
{
	RCC->APB2ENR |=RCC_APB2ENR_USART6EN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

	GPIOC->MODER |= (0b10 << 6*2);//TX
	GPIOC->MODER |= (0b10 << 7*2);//RX
	GPIOC->OSPEEDR |= (0b11 << 6*2)| (0b11 << 7*2);

	GPIOC->AFR[0] |= (8 << 24);
	GPIOC->AFR[0] |= (8 << 28);

	USART6->CR1 |= USART_CR1_UE;
	USART6->BRR = 1667;
	USART6->CR1 |= (0b00 << 28);
	USART6->CR1 |= USART_CR1_TE;
	USART6->CR1 |= USART_CR1_RE;
}

void Usart6_SendChar(uint8_t c)
{
	USART6->TDR = c;
	while(!(USART6->ISR & (1 << 6)));
}

uint8_t Get_Char(void)
{
	uint8_t temp;
	while(!(USART6->ISR & (1<<5)));
	temp = USART6->RDR;
	return temp;
}

int main(void)
{
  Usart6Config();
  Usart6_SendChar(10);
  uint8_t res = 5;
  res = Get_Char();
}
